### ISSUE TITLE
More offline testing

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#10]
Dany L. encountered some problems when first getting going with the app. Part of that seemed to be crashes related to being offline. Being offline should not cause the app to crash. This needs more testing.

**Comment by crspybits** [comment]
What conditions are we testing for here?

**Comment by danligas** [comment]
I typically experience this after leaving my ipad lying around for a week
or so. Upon first unlocking the ipad, I click on shared images to catch up
on my images, and I get "the message".

**Comment by crspybits** [comment]
What is "the message"? This seems like a loss of sticky sign-in issue. Something I've been seeing too.

**Comment by crspybits** [comment]
Closing because this is too generic. Make sure new issues are more specific.
