### ISSUE TITLE
Progress indication when downloading images

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#12]
Currently, when downloading a large number of images (e.g., when first installing the app, and sharing images with someone who has a lot of images), there is no in-progress indication aside from the spinner. It would be good to have a UI indication somehow relating a) the number of images that are being downloaded and b) the number that have already been downloaded.

**Comment by crspybits** [comment]
It seems we need more than this actually:

1) When the number of images grows larger, the initial download (or redownload) can take appreciable time. It seems important to be able to do this incrementally. I.e., instead of waiting for all the images to be downloaded before showing the user, show them the images as they show up. This speaks to at least a different means of using the client API, if not a conceptual change. Previously, I didn't want to expose the files to the user until the download was fully successful in case somewhere along the line of all the downloads, the `masterVersion` changed. However, this is not practical. If 100 images were successfully downloaded (and there were only 101 images), you don't want to have restart. If 100 images were successfully downloaded and 1 had changed at the very end, again, you don't want to have to re download all of those.

2) Dany is running into an issue where something like the above is happening. A number of downloads are successful (as seen from the server logs), but he never sees any of the images because I'm using an all-or-nothing proposition.

It seems we need both:
1) A UI indication to the user of something like N out of a total of M images have been downloaded, and
2) Actual retention of the downloaded images so that if you are forced to restart the app, the download begins again where it left off.

**Comment by danligas** [comment]
Thumbs up on this suggestion. My iPad takes considerably longer given it is
an older model. I did have to uninstall before it would show a non-red
progress indicator. Overnight, the pictures did seem to refresh correctly,
but it is also unclear if I close the lid early in the refresh process if
it ever finishes. I can experiment with that next.

**Comment by crspybits** [comment]
Thanks, Dany. I doubt anything good will happen if you close the lid or put the app into the background. I've not spent time with that yet. Just made a note about that-- https://github.com/crspybits/SharedImages/issues/36

**Comment by crspybits** [comment]
And here are the conceptual issues in more detail:
http://www.spasticmuffin.biz/blog/2017/09/15/making-downloads-more-flexible-in-the-syncserver/
