### ISSUE TITLE
Crashes lately

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#131]
1) Rod-- when he was zooming in on an image
2) Dany-- when he was downloading images when the app was installed on a new device
3) Natasha-- IIRC, when she was looking at the discussion for an image.

Need to upload the dSyms's for the app to Crashlytics and get the crash reports.

**Comment by danligas** [comment]
At the time of my crash, the first time download had been running for 1
hour. It felt like a timeout. When I re-launched and resumed, it felt like
another 2 hours was needed to fully download the current set of images.

**Comment by crspybits** [comment]
On Dany's issue-- looking at the logs, I found https://github.com/crspybits/SyncServerII/issues/89. Dany suggests "Seems to me that the si crash was some aggregated by the slow download. Possibly some sort of unhandled timeout?".

**Comment by crspybits** [comment]
Possibly, the app went into the background on Dany's downloads because the screen locked? I have to check, but I think apps do go into the background when the screen locks. SharedImages really needs to be handling background downloads better. See https://stackoverflow.com/questions/29029632/is-an-ios-app-active-when-the-device-is-locked and https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforHandlingAppStateTransitions/StrategiesforHandlingAppStateTransitions.html

**Comment by crspybits** [comment]
Another from Dany: 
Getting the network not available symbol when trying to refresh “shared images”.
I tried restarting the app.
How I got in this situation was to start a refresh last night (new version) and then close the iPad. This morning I tried to continue it, but it kept not progressing.

**Comment by danligas** [comment]
Symbol was not "network not available". It was the nothing to download.
Working as designed.

**Comment by crspybits** [comment]
The crashes look like they should be from v0.19.0 of the app. However, when I upload the dSyms for this, I get no crashes reported with Crashlytics. Yarg.

**Comment by crspybits** [comment]
Don't have enough info to take this further.
