### ISSUE TITLE
Share image in other ways

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#17]
Apps like Photos enable you to share images in various ways: 
![img_2739](https://user-images.githubusercontent.com/5758762/29094475-abc251a4-7c4a-11e7-894f-5c8fd504a584.PNG)

we need something like that here.

**Comment by danligas** [comment]
Yes, get a hook into the "share" (I think it's a global for all apps that
support sharing out. Your app would be a sink to the share event.

On Tue, Aug 8, 2017 at 5:02 PM, Christopher Prince <notifications@github.com

**Comment by danligas** [comment]
https://developer.apple.com/ios/human-interface-guidelines/extensions/sharing-and-actions/

**Comment by crspybits** [comment]
This is the general technique I'm going to use: https://www.raywenderlich.com/133825/uiactivityviewcontroller-tutorial
