### ISSUE TITLE
Reconsider spinners

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#22]
Currently there are two spinners-- one when you pull down to refresh, and another at the bottom along the tab. Should there really be two spinners? What if we just used the pull-down-to-refresh spinner. It would have to stay present for potentially long periods of time while the upload or download activity happened. If we stay with 2 spinners, having the second spinner on the bottom tab row seems to take it out of reach of the eyes. I had this spinner previously in the upper left, and it seemed more evident there. If I moved it back to the upper left, I'd need to either find another place for the sort control or make that control smaller. E.g., one of those up-arrow controls which I think just designates action.

**Comment by danligas** [comment]
There is another issue open that would deprecated the refresh function.
Background check for new images. When the app opens, it would auto refresh.
The bottom spinner would suffice for that.

**Comment by crspybits** [comment]
Nodding. Good point. And when the autorefresh happens I'm not sure we'd want to magically pull down the pull-down refresh spinner.
