### ISSUE TITLE
Deleting someone elses images crashes app

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#28]
Rod: I deleted two of my pics and that worked ok
Then at Dan's request, I deleted one of his, and it crashed.

**Comment by crspybits** [comment]
I am not sure if this the same issue, but I just reproduced a crash by selecting two images, and attempting to delete them. This is using v 0.7.

**Comment by danligas** [comment]
Where they your own images, or someone else?

**Comment by crspybits** [comment]
They were mine. You guys should post some images you don't mind me deleting. Have you been able to consistently get a crash each time you attempt to delete someone **else's** image?

**Comment by crspybits** [comment]
This is still an issue, though I'm not convinced it's deleting someone else's images per se. See my file Shared Images Crash 10-1-17.txt (I'm not posting it because it has some private identifiers in it).

**Comment by crspybits** [comment]
I suspect I've fixed this now too.
