### ISSUE TITLE
Crashes on using Share Button

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#29]
Dany: Crashed after attempting to hit the share button. No diagnostic information on my end. i.e., the `Share` button on the sign-in screen.

**Comment by danligas** [comment]
Just replicated the issue after restarting app and selecting one image. I have never successfully hit the share button. It could be the version of ios.

**Comment by crspybits** [comment]
@danligas I'm confused by `Just replicated the issue after restarting app and selecting one image.` The `Share` button on the SignIn screen does not relate to selecting images.

**Comment by danligas** [comment]
I mean that I closed the app, and launched it again. Then selected an image
and hit the share button. Crash.

**Comment by crspybits** [comment]
Here's the culprit. https://stackoverflow.com/questions/34404782/uiactivityviewcontroller-not-working-on-ipad-ios-8
