### ISSUE TITLE
Allow chat like discussion upon image drill down

### ISSUE THREAD

**Issue by danligas** [crspybits/SharedImages#3]
Consider a comments section where those users sharing a common image can opine or annotate an image. ie. "awsome bike, load runner"

**Comment by crspybits** [comment]
In terms of development, there are two basic places this chat discussion could be placed:
1) Each file (e.g., image) has an app-specific meta-data field in the server (e.g., this where the current username caption is being stored). For the SharedImages app this is being stored as JSON currently in a String field in the mySQL db (though I've learned recently there are actual JSON columns-- so we could likely switch to that).  We could add a new field into that JSON structure for the chat discussion. A downside of this is that it does get stored in the mySQL database, and not in the owning users cloud storage  so could expand the storage requirements.

2) An alternative to this above would be to have a chat discussion text file paired with each image file. This could be in JSON format. This would have the benefit of (a) storing the chat data also in the owning users cloud storage, and (b) not adding to the size of data in mySQL (something I'm trying to avoid).

**Comment by danligas** [comment]
In support of #2, there are libraries that allow the management of json in individual files. This side file could hold more than the current conversation.
