### ISSUE TITLE
Enable access to images if network is offline, app starts, and you were previously signed-in.

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#30]
RE: https://github.com/crspybits/SharedImages/issues/10

Currently, if you:

1) were signed in,
2) you close (i.e., kill) the app, 
3) lose network connectivity (e.g., go into airplane mode), 
4) relaunch the app.
THEN: 
You will no longer have access to your images. You should have access to them.

**Comment by crspybits** [comment]
Dany: BTW, every[time] I open the app after days of not using it,I must login.

I'm hoping that I solve this with this issue.

**Comment by danligas** [comment]
the new update works like a champ. force complete, and sudden use passed.

**Comment by crspybits** [comment]
@danligas This update wasn't supposed to fix this particular issue! :).

**Comment by crspybits** [comment]
I just built a SharedImages version onto an iPad running iOS 9 and see:

2017-10-22 12:04:04.045 SharedImages[1068:900648] Network.initializeClass: Network is reachable: 0
2017-10-22 12:04:04.045 SharedImages[1068:900648] Network.initializeClass: Network reachability changed
12:04:04.423 ❤️ ERROR Log.error():85 - 2017-10-22 18:04:04 +0000: Error signing into Google: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSErrorFailingURLStringKey=https://www.googleapis.com/oauth2/v4/token, _kCFStreamErrorCodeKey=8, NSErrorFailingURLKey=https://www.googleapis.com/oauth2/v4/token, NSLocalizedDescription=The Internet connection appears to be offline., _kCFStreamErrorDomainKey=12, NSUnderlyingError=0x156c85b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8}}} [sign(_:didSignInFor:withError:) in GoogleSignIn.swift, line 307]

**Comment by crspybits** [comment]
Another thought. In the code, I'm pretty aggressive about signing the user out when I encounter an error. Not recalling exactly why. Need to review those decisions. If, for example, the app couldn't get network connectivity, it would get an error, thus meaning that the user would be signed out and have to sign back in again.

**Comment by crspybits** [comment]
In general, I have two goals here:
1) Enable the user to access their images when offline
2) Don't be so aggressive about signing the user out when an error occurs.

**Comment by crspybits** [comment]
TODO:
1. Need to distinguish between "user was signed in during last launch" and "user is signed in this launch" states.
2. Enable the images tab to be accessed in either of those two states above.
