### ISSUE TITLE
Version 0.8 Issues: Lotties Bottom

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#41]
There are issues with LottiesBottom:
1) On my iPad Air, the top of at least the "C" animation gets clipped off. I should make the animation area slightly higher.
2) At least on iPad, if you launch the app in landscape mode (or enter the images screen in landscape mode the first time), and then rotate to portrait, the animation area for LottiesBottom is then positioned too high, and is not horizontally centered. Need to account for rotation.
3) See https://github.com/crspybits/SharedImages/issues/52

**Comment by crspybits** [comment]
3. (Kudos to Dany):

![c on settings](https://user-images.githubusercontent.com/5758762/31060491-447ec45c-a6d2-11e7-8d2f-82375efac172.jpg)

**Comment by crspybits** [comment]
4. (Kudos to Dany)-- The letter may stay on the screen after the refresh.

**Comment by danligas** [comment]
Even without switching to settings. It stays until I move the screen.
Sometimes I get a small stick without the full letter.
