### ISSUE TITLE
Narrow images.

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#6]
If you add an image that is tall and skinny (and probably short and fat), you the image can't be zoomed properly. (at least with the tall and skinny). With the tall and skinny too, there isn't enough horizontal space to display a decent caption either.

**Comment by danligas** [comment]
Could it be something about         let proportion:CGFloat = 0.30
line 459 of imagescv?

**Comment by crspybits** [comment]
That file is for displaying the small sized images (the first screen), so I don't think so. This issue as I see it has to do with the large images and the zooming. There is the question of not having the caption on the small images-- but this doesn't have to do with the 30% proportion me thinks.

**Comment by danligas** [comment]
At the moment I am unable to see rod's images. I sent earlier screenshot
with red circle.
