### ISSUE TITLE
Badges on initial download

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#83]
Should I just leave the badges in place for a first time download? Or perhaps if I'm going to do that they should just be entirely hidden. What may be distracting is that the badges are there initially and then removed.

**Comment by crspybits** [comment]
The main use case for this issue is users which first get invited to a collection of images. In that case, perhaps it's appropriate for the unread counts to read the actual number of messages. Since the user hasn't read the messages at that point.

**Comment by crspybits** [comment]
Also-- I did get some pushback from Dany on this.

**Comment by danligas** [comment]
Unread messages only show the badge. Small badge, on the main image list,
if the number of messages unread is > 10 (idea is if you are ignoring an
image/conversation, no need to take up more space).
