### ISSUE TITLE
While there is an image upload running, start another: Test Me

### ISSUE THREAD

**Issue by crspybits** [crspybits/SharedImages#87]
This is now possible with the new progress indicator. Try it. Make sure it works.

**Comment by crspybits** [comment]
How do I make sure that the 1st upload is sufficiently slow running to enable me to get the second one started? Can try:
1) Network settings with the Simulator or the phone
2) A relatively large image file.

And then, from the server logs, can make sure that the goal was achieved-- that the second upload started prior to the first ending.

Need to add this as a test case in the Google Sheet with the tests.

**Comment by danligas** [comment]
Consider bandwidth limiter as a service within the sync server. When you
have a large population of users, you may want to prevent starvation due to
misbehaving clients.

**Comment by crspybits** [comment]
Tested.

**Comment by crspybits** [comment]
(Thanks for your comment Dany. This was purely for a test case to queue a 2nd upload while the first was running and I ensured  a slow down using the Mac OS network link conditioner).
